### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by lizhuangs** [17307/ptTools#3]
1、这个插件与浏览器自带的导出har文件有何区别，仅仅是多了记录全部标签页的功能？
2、火狐浏览器新推出了：·[firefox-replay](https://firefox-replay.com/)，这个插件可以保存请求，包括参数和控制台信息等，相当于对使用者当时的请求环境进行了离线的重现，而har是把以前的请求再请求了一遍（此时后台或者页面可能已经修改了）。感觉很强大。

**Comment by 17307** [comment]
- 这个可以记录，并且根据记录修改内容，重放等。直接使用hackbar等也一样，只是需要完全自己输入内容。
- 火狐这个没有过多了解。
